#!/bin/bash

EVENT=$1

HASS_URL="http://10.0.0.76:8123/api/states/input_boolean.mac_ext_speakers"
source /Users/caleb/dev/personal/smarthome/.env
TOKEN="$hass_token"

turn_on() {
  curl \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-type: application/json" \
    -d '{"state": "on"}' \
    $HASS_URL
}
turn_off() {
  curl \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-type: application/json" \
    -d '{"state": "off"}' \
    $HASS_URL
}
if /Users/caleb/dev/personal/smarthome/power_event_watcher/interface_connected | grep -q "true"; then
  if [ "$EVENT" == "off" ]; then
    turn_off
  elif [ "$EVENT" == "on" ]; then
    turn_on
  fi
fi
