#!/bin/bash

EVENT=$1

HASS_URL="http://10.0.0.76:8123/api/states/input_boolean.mac_ext_speakers"
TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIxOGU5OTJkZjY5N2Y0MGQ4YjlkYzkxOGMwNGE1YWIwZiIsImlhdCI6MTcxOTQxMTc4OSwiZXhwIjoyMDM0NzcxNzg5fQ.1KG_Akil2HMgHUnxxQ2D0Neyknl8BzrKJt_YQ44ZPy8"

turn_on() {
curl \
      -H "Authorization: Bearer $TOKEN" \
      -H "Content-type: application/json" \
      -d '{"state": "on"}' \
      $HASS_URL
}
turn_off() {
curl \
      -H "Authorization: Bearer $TOKEN" \
      -H "Content-type: application/json" \
      -d '{"state": "off"}' \
      $HASS_URL
}

is_connected() {
system_profiler SPUSBDataType | grep -q '0x2902' # USB CODEC Product ID
}

if is_connected; then
  if [ "$EVENT" == "off" ]; then
    turn_off
  elif [ "$EVENT" == "on" ]; then
    turn_on
  fi
fi

