#!/bin/bash

EVENT=$1
source /Users/caleb/dev/personal/smarthome/.env

HASS_URL="http://10.0.0.76:8123/api/states/input_boolean.mac_ext_speakers"
TOKEN="$hass_token"

turn_on() {
  curl \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-type: application/json" \
    -d '{"state": "on"}' \
    $HASS_URL
}
turn_off() {
  curl \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-type: application/json" \
    -d '{"state": "off"}' \
    $HASS_URL
}

is_connected() {
  system_profiler SPUSBDataType | grep -q '0x2902' # USB CODEC Product ID
}

if is_connected; then
  if [ "$EVENT" == "off" ]; then
    turn_off
  elif [ "$EVENT" == "on" ]; then
    turn_on
  fi
fi
